server:
  port: 8081

mysql:
  dsn: "root:Xy8@Kp3!Mv9#Jq@tcp(43.136.50.116:9801)/campus?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai"
  max_lifetime: 60000

mongo:
  uri: "mongodb://admin:F6m%40t3YhexitRu9k@43.136.50.116:9803/campus?authSource=admin"
  database: "campus"

redis:
  addr: "43.136.50.116:9800"
  password: "B6yz7P@x9d&."
  db: 0

jwt:
  secret: "@12asd."
  token_minutes: 60
  refresh_token_minutes: 2880
  issue: "campus"

encryption:
  key: "W0F7PePvolUJHmZtkv1MusWpwhpVJIJI"

admin:
  power_sign: 999
  secondary_password: "replace-me"

logging:
  level: "info"
  file_path: "logs/ecampus-crm.log"
