server:
  port: 8081

mysql:
  dsn: "root:password@tcp(mysql:3306)/campus?charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai"

mongo:
  uri: "mongodb://admin:password@mongo:27017/campus?authSource=admin"
  database: "campus"

redis:
  addr: "redis:6379"
  password: "password"
  db: 0

logging:
  level: "info"
  file_path: "logs/ecampus-crm-dev.log"
