apiVersion: v1
kind: ConfigMap
metadata:
  name: buildkitd-config
  namespace: delivery
data:
  buildkitd.toml: |
    [worker.oci]
      gc = true
      reservedSpace = "4GB"
      maxUsedSpace = "10GB"
      minFreeSpace = "3GB"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildkit-cache
  namespace: delivery
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
