// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Domain int32

const (
	Domain_DOMAIN_UNSPECIFIED Domain = 0
	Domain_DOMAIN_CHAT        Domain = 1
	Domain_DOMAIN_MATCHMAKER  Domain = 2
	Domain_DOMAIN_INTERVIEW   Domain = 3
)

// Enum value maps for Domain.
var (
	Domain_name = map[int32]string{
		0: "DOMAIN_UNSPECIFIED",
		1: "DOMAIN_CHAT",
		2: "DOMAIN_MATCHMAKER",
		3: "DOMAIN_INTERVIEW",
	}
	Domain_value = map[string]int32{
		"DOMAIN_UNSPECIFIED": 0,
		"DOMAIN_CHAT":        1,
		"DOMAIN_MATCHMAKER":  2,
		"DOMAIN_INTERVIEW":   3,
	}
)

func (x Domain) Enum() *Domain {
	p := new(Domain)
	*p = x
	return p
}

func (x Domain) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Domain) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (Domain) Type() protoreflect.EnumType {
	return &file_proto_agent_v1_agent_proto_enumTypes[0]
}

func (x Domain) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Domain.Descriptor instead.
func (Domain) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

type Intent int32

const (
	Intent_INTENT_UNSPECIFIED    Intent = 0
	Intent_INTENT_CHAT_GENERAL   Intent = 1
	Intent_INTENT_MATCHMAKER     Intent = 2
	Intent_INTENT_INTERVIEW_MOCK Intent = 5
)

// Enum value maps for Intent.
var (
	Intent_name = map[int32]string{
		0: "INTENT_UNSPECIFIED",
		1: "INTENT_CHAT_GENERAL",
		2: "INTENT_MATCHMAKER",
		5: "INTENT_INTERVIEW_MOCK",
	}
	Intent_value = map[string]int32{
		"INTENT_UNSPECIFIED":    0,
		"INTENT_CHAT_GENERAL":   1,
		"INTENT_MATCHMAKER":     2,
		"INTENT_INTERVIEW_MOCK": 5,
	}
)

func (x Intent) Enum() *Intent {
	p := new(Intent)
	*p = x
	return p
}

func (x Intent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Intent) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_v1_agent_proto_enumTypes[1].Descriptor()
}

func (Intent) Type() protoreflect.EnumType {
	return &file_proto_agent_v1_agent_proto_enumTypes[1]
}

func (x Intent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Intent.Descriptor instead.
func (Intent) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

type Mode int32

const (
	Mode_MODE_UNSPECIFIED Mode = 0
	Mode_MODE_FASTPATH    Mode = 1
	Mode_MODE_GENERATE    Mode = 2
	Mode_MODE_DEGRADED    Mode = 3
)

// Enum value maps for Mode.
var (
	Mode_name = map[int32]string{
		0: "MODE_UNSPECIFIED",
		1: "MODE_FASTPATH",
		2: "MODE_GENERATE",
		3: "MODE_DEGRADED",
	}
	Mode_value = map[string]int32{
		"MODE_UNSPECIFIED": 0,
		"MODE_FASTPATH":    1,
		"MODE_GENERATE":    2,
		"MODE_DEGRADED":    3,
	}
)

func (x Mode) Enum() *Mode {
	p := new(Mode)
	*p = x
	return p
}

func (x Mode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_v1_agent_proto_enumTypes[2].Descriptor()
}

func (Mode) Type() protoreflect.EnumType {
	return &file_proto_agent_v1_agent_proto_enumTypes[2]
}

func (x Mode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mode.Descriptor instead.
func (Mode) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

type CapabilityHint int32

const (
	CapabilityHint_CAPABILITY_HINT_UNSPECIFIED CapabilityHint = 0
	CapabilityHint_CAPABILITY_HINT_CHAT        CapabilityHint = 1
	CapabilityHint_CAPABILITY_HINT_MATCHMAKER  CapabilityHint = 2
	CapabilityHint_CAPABILITY_HINT_INTERVIEW   CapabilityHint = 3
)

// Enum value maps for CapabilityHint.
var (
	CapabilityHint_name = map[int32]string{
		0: "CAPABILITY_HINT_UNSPECIFIED",
		1: "CAPABILITY_HINT_CHAT",
		2: "CAPABILITY_HINT_MATCHMAKER",
		3: "CAPABILITY_HINT_INTERVIEW",
	}
	CapabilityHint_value = map[string]int32{
		"CAPABILITY_HINT_UNSPECIFIED": 0,
		"CAPABILITY_HINT_CHAT":        1,
		"CAPABILITY_HINT_MATCHMAKER":  2,
		"CAPABILITY_HINT_INTERVIEW":   3,
	}
)

func (x CapabilityHint) Enum() *CapabilityHint {
	p := new(CapabilityHint)
	*p = x
	return p
}

func (x CapabilityHint) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CapabilityHint) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_v1_agent_proto_enumTypes[3].Descriptor()
}

func (CapabilityHint) Type() protoreflect.EnumType {
	return &file_proto_agent_v1_agent_proto_enumTypes[3]
}

func (x CapabilityHint) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CapabilityHint.Descriptor instead.
func (CapabilityHint) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED                   ErrorCode = 0
	ErrorCode_ERROR_CODE_INVALID_ARGUMENT              ErrorCode = 1
	ErrorCode_ERROR_CODE_UNAUTHORIZED                  ErrorCode = 2
	ErrorCode_ERROR_CODE_SESSION_NOT_FOUND             ErrorCode = 3
	ErrorCode_ERROR_CODE_UNIMPLEMENTED_CAPABILITY      ErrorCode = 4
	ErrorCode_ERROR_CODE_MODEL_TEMPORARILY_UNAVAILABLE ErrorCode = 5
	ErrorCode_ERROR_CODE_INTERNAL_DEPENDENCY_FAILURE   ErrorCode = 6
	ErrorCode_ERROR_CODE_REQUEST_IN_PROGRESS           ErrorCode = 7
	ErrorCode_ERROR_CODE_INTERNAL                      ErrorCode = 8
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_INVALID_ARGUMENT",
		2: "ERROR_CODE_UNAUTHORIZED",
		3: "ERROR_CODE_SESSION_NOT_FOUND",
		4: "ERROR_CODE_UNIMPLEMENTED_CAPABILITY",
		5: "ERROR_CODE_MODEL_TEMPORARILY_UNAVAILABLE",
		6: "ERROR_CODE_INTERNAL_DEPENDENCY_FAILURE",
		7: "ERROR_CODE_REQUEST_IN_PROGRESS",
		8: "ERROR_CODE_INTERNAL",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":                   0,
		"ERROR_CODE_INVALID_ARGUMENT":              1,
		"ERROR_CODE_UNAUTHORIZED":                  2,
		"ERROR_CODE_SESSION_NOT_FOUND":             3,
		"ERROR_CODE_UNIMPLEMENTED_CAPABILITY":      4,
		"ERROR_CODE_MODEL_TEMPORARILY_UNAVAILABLE": 5,
		"ERROR_CODE_INTERNAL_DEPENDENCY_FAILURE":   6,
		"ERROR_CODE_REQUEST_IN_PROGRESS":           7,
		"ERROR_CODE_INTERNAL":                      8,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_agent_v1_agent_proto_enumTypes[4].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_proto_agent_v1_agent_proto_enumTypes[4]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

type ResponseCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseCard) Reset() {
	*x = ResponseCard{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCard) ProtoMessage() {}

func (x *ResponseCard) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCard.ProtoReflect.Descriptor instead.
func (*ResponseCard) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseCard) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ResponseCard) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *ResponseCard) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Reference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Ref           string                 `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reference) Reset() {
	*x = Reference{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reference) ProtoMessage() {}

func (x *Reference) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reference.ProtoReflect.Descriptor instead.
func (*Reference) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Reference) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Reference) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *Reference) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type StreamStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStatus) Reset() {
	*x = StreamStatus{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStatus) ProtoMessage() {}

func (x *StreamStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStatus.ProtoReflect.Descriptor instead.
func (*StreamStatus) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *StreamStatus) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *StreamStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StreamDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamDelta) Reset() {
	*x = StreamDelta{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDelta) ProtoMessage() {}

func (x *StreamDelta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDelta.ProtoReflect.Descriptor instead.
func (*StreamDelta) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *StreamDelta) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type StreamError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamError) Reset() {
	*x = StreamError{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamError) ProtoMessage() {}

func (x *StreamError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamError.ProtoReflect.Descriptor instead.
func (*StreamError) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *StreamError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StreamError) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type StreamHandleTurnEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*StreamHandleTurnEvent_Status
	//	*StreamHandleTurnEvent_Delta
	//	*StreamHandleTurnEvent_FinalResponse
	//	*StreamHandleTurnEvent_Error
	Event         isStreamHandleTurnEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamHandleTurnEvent) Reset() {
	*x = StreamHandleTurnEvent{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamHandleTurnEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamHandleTurnEvent) ProtoMessage() {}

func (x *StreamHandleTurnEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamHandleTurnEvent.ProtoReflect.Descriptor instead.
func (*StreamHandleTurnEvent) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *StreamHandleTurnEvent) GetEvent() isStreamHandleTurnEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *StreamHandleTurnEvent) GetStatus() *StreamStatus {
	if x != nil {
		if x, ok := x.Event.(*StreamHandleTurnEvent_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *StreamHandleTurnEvent) GetDelta() *StreamDelta {
	if x != nil {
		if x, ok := x.Event.(*StreamHandleTurnEvent_Delta); ok {
			return x.Delta
		}
	}
	return nil
}

func (x *StreamHandleTurnEvent) GetFinalResponse() *HandleTurnResponse {
	if x != nil {
		if x, ok := x.Event.(*StreamHandleTurnEvent_FinalResponse); ok {
			return x.FinalResponse
		}
	}
	return nil
}

func (x *StreamHandleTurnEvent) GetError() *StreamError {
	if x != nil {
		if x, ok := x.Event.(*StreamHandleTurnEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isStreamHandleTurnEvent_Event interface {
	isStreamHandleTurnEvent_Event()
}

type StreamHandleTurnEvent_Status struct {
	Status *StreamStatus `protobuf:"bytes,1,opt,name=status,proto3,oneof"`
}

type StreamHandleTurnEvent_Delta struct {
	Delta *StreamDelta `protobuf:"bytes,2,opt,name=delta,proto3,oneof"`
}

type StreamHandleTurnEvent_FinalResponse struct {
	FinalResponse *HandleTurnResponse `protobuf:"bytes,3,opt,name=final_response,json=finalResponse,proto3,oneof"`
}

type StreamHandleTurnEvent_Error struct {
	Error *StreamError `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*StreamHandleTurnEvent_Status) isStreamHandleTurnEvent_Event() {}

func (*StreamHandleTurnEvent_Delta) isStreamHandleTurnEvent_Event() {}

func (*StreamHandleTurnEvent_FinalResponse) isStreamHandleTurnEvent_Event() {}

func (*StreamHandleTurnEvent_Error) isStreamHandleTurnEvent_Event() {}

type ConversationTurn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SequenceNo    int64                  `protobuf:"varint,1,opt,name=sequence_no,json=sequenceNo,proto3" json:"sequence_no,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Domain        Domain                 `protobuf:"varint,5,opt,name=domain,proto3,enum=agent.v1.Domain" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationTurn) Reset() {
	*x = ConversationTurn{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationTurn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationTurn) ProtoMessage() {}

func (x *ConversationTurn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationTurn.ProtoReflect.Descriptor instead.
func (*ConversationTurn) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ConversationTurn) GetSequenceNo() int64 {
	if x != nil {
		return x.SequenceNo
	}
	return 0
}

func (x *ConversationTurn) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ConversationTurn) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ConversationTurn) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ConversationTurn) GetDomain() Domain {
	if x != nil {
		return x.Domain
	}
	return Domain_DOMAIN_UNSPECIFIED
}

type GetSessionHistoryRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId        string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	BeforeSequenceNo int64                  `protobuf:"varint,3,opt,name=before_sequence_no,json=beforeSequenceNo,proto3" json:"before_sequence_no,omitempty"`
	Limit            int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetSessionHistoryRequest) Reset() {
	*x = GetSessionHistoryRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionHistoryRequest) ProtoMessage() {}

func (x *GetSessionHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetSessionHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *GetSessionHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetSessionHistoryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetSessionHistoryRequest) GetBeforeSequenceNo() int64 {
	if x != nil {
		return x.BeforeSequenceNo
	}
	return 0
}

func (x *GetSessionHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetSessionHistoryResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Turns                []*ConversationTurn    `protobuf:"bytes,1,rep,name=turns,proto3" json:"turns,omitempty"`
	HasMore              bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	NextBeforeSequenceNo int64                  `protobuf:"varint,3,opt,name=next_before_sequence_no,json=nextBeforeSequenceNo,proto3" json:"next_before_sequence_no,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetSessionHistoryResponse) Reset() {
	*x = GetSessionHistoryResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionHistoryResponse) ProtoMessage() {}

func (x *GetSessionHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetSessionHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *GetSessionHistoryResponse) GetTurns() []*ConversationTurn {
	if x != nil {
		return x.Turns
	}
	return nil
}

func (x *GetSessionHistoryResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *GetSessionHistoryResponse) GetNextBeforeSequenceNo() int64 {
	if x != nil {
		return x.NextBeforeSequenceNo
	}
	return 0
}

type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DeleteSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionResponse) Reset() {
	*x = DeleteSessionResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionResponse) ProtoMessage() {}

func (x *DeleteSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteSessionResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type HandleTurnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Utterance     string                 `protobuf:"bytes,4,opt,name=utterance,proto3" json:"utterance,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DeadlineMs    int64                  `protobuf:"varint,7,opt,name=deadline_ms,json=deadlineMs,proto3" json:"deadline_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleTurnRequest) Reset() {
	*x = HandleTurnRequest{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleTurnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleTurnRequest) ProtoMessage() {}

func (x *HandleTurnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleTurnRequest.ProtoReflect.Descriptor instead.
func (*HandleTurnRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *HandleTurnRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HandleTurnRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *HandleTurnRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HandleTurnRequest) GetUtterance() string {
	if x != nil {
		return x.Utterance
	}
	return ""
}

func (x *HandleTurnRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *HandleTurnRequest) GetDeadlineMs() int64 {
	if x != nil {
		return x.DeadlineMs
	}
	return 0
}

type HandleTurnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        Domain                 `protobuf:"varint,1,opt,name=domain,proto3,enum=agent.v1.Domain" json:"domain,omitempty"`
	Intent        Intent                 `protobuf:"varint,2,opt,name=intent,proto3,enum=agent.v1.Intent" json:"intent,omitempty"`
	Mode          Mode                   `protobuf:"varint,3,opt,name=mode,proto3,enum=agent.v1.Mode" json:"mode,omitempty"`
	AnswerText    string                 `protobuf:"bytes,4,opt,name=answer_text,json=answerText,proto3" json:"answer_text,omitempty"`
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Degraded      bool                   `protobuf:"varint,6,opt,name=degraded,proto3" json:"degraded,omitempty"`
	DegradeReason string                 `protobuf:"bytes,7,opt,name=degrade_reason,json=degradeReason,proto3" json:"degrade_reason,omitempty"`
	ErrorCode     ErrorCode              `protobuf:"varint,8,opt,name=error_code,json=errorCode,proto3,enum=agent.v1.ErrorCode" json:"error_code,omitempty"`
	Cards         []*ResponseCard        `protobuf:"bytes,9,rep,name=cards,proto3" json:"cards,omitempty"`
	References    []*Reference           `protobuf:"bytes,10,rep,name=references,proto3" json:"references,omitempty"`
	CapabilityId  string                 `protobuf:"bytes,11,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleTurnResponse) Reset() {
	*x = HandleTurnResponse{}
	mi := &file_proto_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleTurnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleTurnResponse) ProtoMessage() {}

func (x *HandleTurnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleTurnResponse.ProtoReflect.Descriptor instead.
func (*HandleTurnResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *HandleTurnResponse) GetDomain() Domain {
	if x != nil {
		return x.Domain
	}
	return Domain_DOMAIN_UNSPECIFIED
}

func (x *HandleTurnResponse) GetIntent() Intent {
	if x != nil {
		return x.Intent
	}
	return Intent_INTENT_UNSPECIFIED
}

func (x *HandleTurnResponse) GetMode() Mode {
	if x != nil {
		return x.Mode
	}
	return Mode_MODE_UNSPECIFIED
}

func (x *HandleTurnResponse) GetAnswerText() string {
	if x != nil {
		return x.AnswerText
	}
	return ""
}

func (x *HandleTurnResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *HandleTurnResponse) GetDegraded() bool {
	if x != nil {
		return x.Degraded
	}
	return false
}

func (x *HandleTurnResponse) GetDegradeReason() string {
	if x != nil {
		return x.DegradeReason
	}
	return ""
}

func (x *HandleTurnResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *HandleTurnResponse) GetCards() []*ResponseCard {
	if x != nil {
		return x.Cards
	}
	return nil
}

func (x *HandleTurnResponse) GetReferences() []*Reference {
	if x != nil {
		return x.References
	}
	return nil
}

func (x *HandleTurnResponse) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

var File_proto_agent_v1_agent_proto protoreflect.FileDescriptor

const file_proto_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/agent/v1/agent.proto\x12\bagent.v1\"J\n" +
	"\fResponseCard\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"K\n" +
	"\tReference\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x10\n" +
	"\x03ref\x18\x02 \x01(\tR\x03ref\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\">\n" +
	"\fStreamStatus\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"!\n" +
	"\vStreamDelta\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"B\n" +
	"\vStreamError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\"\xf7\x01\n" +
	"\x15StreamHandleTurnEvent\x120\n" +
	"\x06status\x18\x01 \x01(\v2\x16.agent.v1.StreamStatusH\x00R\x06status\x12-\n" +
	"\x05delta\x18\x02 \x01(\v2\x15.agent.v1.StreamDeltaH\x00R\x05delta\x12E\n" +
	"\x0efinal_response\x18\x03 \x01(\v2\x1c.agent.v1.HandleTurnResponseH\x00R\rfinalResponse\x12-\n" +
	"\x05error\x18\x04 \x01(\v2\x15.agent.v1.StreamErrorH\x00R\x05errorB\a\n" +
	"\x05event\"\xaa\x01\n" +
	"\x10ConversationTurn\x12\x1f\n" +
	"\vsequence_no\x18\x01 \x01(\x03R\n" +
	"sequenceNo\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12(\n" +
	"\x06domain\x18\x05 \x01(\x0e2\x10.agent.v1.DomainR\x06domain\"\x96\x01\n" +
	"\x18GetSessionHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12,\n" +
	"\x12before_sequence_no\x18\x03 \x01(\x03R\x10beforeSequenceNo\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x9f\x01\n" +
	"\x19GetSessionHistoryResponse\x120\n" +
	"\x05turns\x18\x01 \x03(\v2\x1a.agent.v1.ConversationTurnR\x05turns\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x125\n" +
	"\x17next_before_sequence_no\x18\x03 \x01(\x03R\x14nextBeforeSequenceNo\"N\n" +
	"\x14DeleteSessionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"1\n" +
	"\x15DeleteSessionResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"\xf7\x02\n" +
	"\x11HandleTurnRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1c\n" +
	"\tutterance\x18\x04 \x01(\tR\tutterance\x12E\n" +
	"\bmetadata\x18\x06 \x03(\v2).agent.v1.HandleTurnRequest.MetadataEntryR\bmetadata\x12\x1f\n" +
	"\vdeadline_ms\x18\a \x01(\x03R\n" +
	"deadlineMs\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x05\x10\x06J\x04\b\b\x10\tJ\x04\b\t\x10\n" +
	"R\x0fcapability_hintR\rcapability_idR\x16allowed_capability_ids\"\xc7\x03\n" +
	"\x12HandleTurnResponse\x12(\n" +
	"\x06domain\x18\x01 \x01(\x0e2\x10.agent.v1.DomainR\x06domain\x12(\n" +
	"\x06intent\x18\x02 \x01(\x0e2\x10.agent.v1.IntentR\x06intent\x12\"\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x0e.agent.v1.ModeR\x04mode\x12\x1f\n" +
	"\vanswer_text\x18\x04 \x01(\tR\n" +
	"answerText\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x12\x1a\n" +
	"\bdegraded\x18\x06 \x01(\bR\bdegraded\x12%\n" +
	"\x0edegrade_reason\x18\a \x01(\tR\rdegradeReason\x122\n" +
	"\n" +
	"error_code\x18\b \x01(\x0e2\x13.agent.v1.ErrorCodeR\terrorCode\x12,\n" +
	"\x05cards\x18\t \x03(\v2\x16.agent.v1.ResponseCardR\x05cards\x123\n" +
	"\n" +
	"references\x18\n" +
	" \x03(\v2\x13.agent.v1.ReferenceR\n" +
	"references\x12#\n" +
	"\rcapability_id\x18\v \x01(\tR\fcapabilityId*^\n" +
	"\x06Domain\x12\x16\n" +
	"\x12DOMAIN_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vDOMAIN_CHAT\x10\x01\x12\x15\n" +
	"\x11DOMAIN_MATCHMAKER\x10\x02\x12\x14\n" +
	"\x10DOMAIN_INTERVIEW\x10\x03*\xc9\x01\n" +
	"\x06Intent\x12\x16\n" +
	"\x12INTENT_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13INTENT_CHAT_GENERAL\x10\x01\x12\x15\n" +
	"\x11INTENT_MATCHMAKER\x10\x02\x12\x19\n" +
	"\x15INTENT_INTERVIEW_MOCK\x10\x05\"\x04\b\x03\x10\x03\"\x04\b\x04\x10\x04*\x1cINTENT_MATCHMAKER_FIND_SKILL*\x1bINTENT_MATCHMAKER_FIND_ITEM*\x15INTENT_MATCHMAKER_FAQ*U\n" +
	"\x04Mode\x12\x14\n" +
	"\x10MODE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rMODE_FASTPATH\x10\x01\x12\x11\n" +
	"\rMODE_GENERATE\x10\x02\x12\x11\n" +
	"\rMODE_DEGRADED\x10\x03*\x8a\x01\n" +
	"\x0eCapabilityHint\x12\x1f\n" +
	"\x1bCAPABILITY_HINT_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14CAPABILITY_HINT_CHAT\x10\x01\x12\x1e\n" +
	"\x1aCAPABILITY_HINT_MATCHMAKER\x10\x02\x12\x1d\n" +
	"\x19CAPABILITY_HINT_INTERVIEW\x10\x03*\xc7\x02\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bERROR_CODE_INVALID_ARGUMENT\x10\x01\x12\x1b\n" +
	"\x17ERROR_CODE_UNAUTHORIZED\x10\x02\x12 \n" +
	"\x1cERROR_CODE_SESSION_NOT_FOUND\x10\x03\x12'\n" +
	"#ERROR_CODE_UNIMPLEMENTED_CAPABILITY\x10\x04\x12,\n" +
	"(ERROR_CODE_MODEL_TEMPORARILY_UNAVAILABLE\x10\x05\x12*\n" +
	"&ERROR_CODE_INTERNAL_DEPENDENCY_FAILURE\x10\x06\x12\"\n" +
	"\x1eERROR_CODE_REQUEST_IN_PROGRESS\x10\a\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10\b2\xdb\x02\n" +
	"\fAgentService\x12G\n" +
	"\n" +
	"HandleTurn\x12\x1b.agent.v1.HandleTurnRequest\x1a\x1c.agent.v1.HandleTurnResponse\x12R\n" +
	"\x10StreamHandleTurn\x12\x1b.agent.v1.HandleTurnRequest\x1a\x1f.agent.v1.StreamHandleTurnEvent0\x01\x12\\\n" +
	"\x11GetSessionHistory\x12\".agent.v1.GetSessionHistoryRequest\x1a#.agent.v1.GetSessionHistoryResponse\x12P\n" +
	"\rDeleteSession\x12\x1e.agent.v1.DeleteSessionRequest\x1a\x1f.agent.v1.DeleteSessionResponseBHZFgithub.com/Milchstrassse/Ecampus-go/internal/agentchat/agentv1;agentv1b\x06proto3"

var (
	file_proto_agent_v1_agent_proto_rawDescOnce sync.Once
	file_proto_agent_v1_agent_proto_rawDescData []byte
)

func file_proto_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_v1_agent_proto_rawDesc), len(file_proto_agent_v1_agent_proto_rawDesc)))
	})
	return file_proto_agent_v1_agent_proto_rawDescData
}

var file_proto_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_proto_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_agent_v1_agent_proto_goTypes = []any{
	(Domain)(0),                       // 0: agent.v1.Domain
	(Intent)(0),                       // 1: agent.v1.Intent
	(Mode)(0),                         // 2: agent.v1.Mode
	(CapabilityHint)(0),               // 3: agent.v1.CapabilityHint
	(ErrorCode)(0),                    // 4: agent.v1.ErrorCode
	(*ResponseCard)(nil),              // 5: agent.v1.ResponseCard
	(*Reference)(nil),                 // 6: agent.v1.Reference
	(*StreamStatus)(nil),              // 7: agent.v1.StreamStatus
	(*StreamDelta)(nil),               // 8: agent.v1.StreamDelta
	(*StreamError)(nil),               // 9: agent.v1.StreamError
	(*StreamHandleTurnEvent)(nil),     // 10: agent.v1.StreamHandleTurnEvent
	(*ConversationTurn)(nil),          // 11: agent.v1.ConversationTurn
	(*GetSessionHistoryRequest)(nil),  // 12: agent.v1.GetSessionHistoryRequest
	(*GetSessionHistoryResponse)(nil), // 13: agent.v1.GetSessionHistoryResponse
	(*DeleteSessionRequest)(nil),      // 14: agent.v1.DeleteSessionRequest
	(*DeleteSessionResponse)(nil),     // 15: agent.v1.DeleteSessionResponse
	(*HandleTurnRequest)(nil),         // 16: agent.v1.HandleTurnRequest
	(*HandleTurnResponse)(nil),        // 17: agent.v1.HandleTurnResponse
	nil,                               // 18: agent.v1.HandleTurnRequest.MetadataEntry
}
var file_proto_agent_v1_agent_proto_depIdxs = []int32{
	7,  // 0: agent.v1.StreamHandleTurnEvent.status:type_name -> agent.v1.StreamStatus
	8,  // 1: agent.v1.StreamHandleTurnEvent.delta:type_name -> agent.v1.StreamDelta
	17, // 2: agent.v1.StreamHandleTurnEvent.final_response:type_name -> agent.v1.HandleTurnResponse
	9,  // 3: agent.v1.StreamHandleTurnEvent.error:type_name -> agent.v1.StreamError
	0,  // 4: agent.v1.ConversationTurn.domain:type_name -> agent.v1.Domain
	11, // 5: agent.v1.GetSessionHistoryResponse.turns:type_name -> agent.v1.ConversationTurn
	18, // 6: agent.v1.HandleTurnRequest.metadata:type_name -> agent.v1.HandleTurnRequest.MetadataEntry
	0,  // 7: agent.v1.HandleTurnResponse.domain:type_name -> agent.v1.Domain
	1,  // 8: agent.v1.HandleTurnResponse.intent:type_name -> agent.v1.Intent
	2,  // 9: agent.v1.HandleTurnResponse.mode:type_name -> agent.v1.Mode
	4,  // 10: agent.v1.HandleTurnResponse.error_code:type_name -> agent.v1.ErrorCode
	5,  // 11: agent.v1.HandleTurnResponse.cards:type_name -> agent.v1.ResponseCard
	6,  // 12: agent.v1.HandleTurnResponse.references:type_name -> agent.v1.Reference
	16, // 13: agent.v1.AgentService.HandleTurn:input_type -> agent.v1.HandleTurnRequest
	16, // 14: agent.v1.AgentService.StreamHandleTurn:input_type -> agent.v1.HandleTurnRequest
	12, // 15: agent.v1.AgentService.GetSessionHistory:input_type -> agent.v1.GetSessionHistoryRequest
	14, // 16: agent.v1.AgentService.DeleteSession:input_type -> agent.v1.DeleteSessionRequest
	17, // 17: agent.v1.AgentService.HandleTurn:output_type -> agent.v1.HandleTurnResponse
	10, // 18: agent.v1.AgentService.StreamHandleTurn:output_type -> agent.v1.StreamHandleTurnEvent
	13, // 19: agent.v1.AgentService.GetSessionHistory:output_type -> agent.v1.GetSessionHistoryResponse
	15, // 20: agent.v1.AgentService.DeleteSession:output_type -> agent.v1.DeleteSessionResponse
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_agent_v1_agent_proto_init() }
func file_proto_agent_v1_agent_proto_init() {
	if File_proto_agent_v1_agent_proto != nil {
		return
	}
	file_proto_agent_v1_agent_proto_msgTypes[5].OneofWrappers = []any{
		(*StreamHandleTurnEvent_Status)(nil),
		(*StreamHandleTurnEvent_Delta)(nil),
		(*StreamHandleTurnEvent_FinalResponse)(nil),
		(*StreamHandleTurnEvent_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_v1_agent_proto_rawDesc), len(file_proto_agent_v1_agent_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_proto_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_proto_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_v1_agent_proto = out.File
	file_proto_agent_v1_agent_proto_goTypes = nil
	file_proto_agent_v1_agent_proto_depIdxs = nil
}
