apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  project: platform-addons

  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: redis
      targetRevision: 22.0.1
      helm:
        releaseName: platform-redis
        valueFiles:
          - $values/k3s/helm-values/platform/redis.yaml
    - repoURL: https://github.com/worryyy/app-test.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: platform

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
